---
## @section Global parameters
## Please, note that this will override the parameters, including dependencies.
##
global:
  ## @param global.imageRegistry Global Docker image registry
  ##
  imageRegistry: ""
  ## @param global.imagePullSecrets Global Docker registry secret names as an array
  ## e.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  ## @param global.storageClass Global StorageClass for Persistent Volume(s)
  ##
  storageClass: ""

  ## TODO: in bitnami charts this contains info on auth and service for postgres, nothing more for keycloak
  ## idk if necessary
  worker:
    service:
      ports:
        worker: ""

  web:
    asd: dsa
  #postgresql:
  #  auth

## @section Common parameters
##

## @param kubeVersion Override Kubernetes version
##
## TODO: idk if necessary
kubeVersion: ""
## @param nameOverride String to partially override common.names.fullname template (will maintain the release name)
##
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname template
##
fullnameOverride: ""
## @param clusterDomain Kubernetes Cluster Domain
##
clusterDomain: cluster.local
## @param extraDeploy Array of extra objects to deploy with the release (evaluated as a template)
##
extraDeploy: []
## @param commonLabels Add labels to all the deployed resources
##
commonLabels: {}
## @param commonAnnotations Add annotations to all the deployed resources
##
commonAnnotations: {}
## Enable diagnostic mode in the statefulset
##
## TODO: will it work with deps? do we need it?
diagnosticMode:
  ## @param diagnosticMode.enabled Enable diagnostic mode (all probes will be disabled and the command will be overridden)
  ##
  enabled: false
  ## @param diagnosticMode.command Command to override all containers in the statefulset
  ##
  command:
    - sleep
  ## @param diagnosticMode.args Args to override all containers in the statefulset
  ##
  args:
    - infinity



# TODO: whole section when official img will be available
## NexB ScanCode.io image version
## ref: https://hub.docker.com/r/bitnami/postgresql/tags/
## @param image.registry ScanCode.io image registry
## @param image.repository ScanCode.io image repository
# TODO: tag should be empty, note it will override deault appVersion tag
## @param image.tag ScanCode.io image tag (immutable tags are recommended)
## @param image.pullPolicy ScanCode.io image pull policy
## @param image.pullSecrets Specify image pull secrets
## @param image.debug Specify if debug values should be set
##
image:
  registry: docker.io
  repository: aalexanderr/scancodeio
  tag: v30.2.0-onap3
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ## Example:
  ## pullSecrets:
  ##   - myRegistryKeySecretName
  ##
  pullSecrets: []
  ## Set to true if you would like to see extra information on logs
  ##
  # TODO: check how it works in bitnami charts
  debug: false


auth:
  # TODO: add a job that will create superuser via manage.py
  createSuperUser: false
  username: ""
  password: ""
  existingSecret: ""


containerPorts:
  web: ""
  worker: ""
  redis: ""
  postgres: 5432

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname
  # template
  name: ""

securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
# We usually recommend not to specify default resources and to leave this
# as a conscious choice for the user. This also increases chances charts
# run on environments with little resources, such as Minikube.
# If you do want to specify resources, uncomment the following
# lines, adjust them as necessary,
# and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

postgresql:
  auth:
    username: scancode-user
    database: scancode-db
    existingSecret: scancode-secret

redis:
  architecture: standalone
  auth:
    enabled: false

nginx:
  ## @param extraVolumes Array to add extra volumes
  ##
  #  extraVolumes:
  #    - name: staticsite
  #      hostPath:
  #        path: /data/static/
  #        type: Directory
  extraVolumes:
    - name: "{{ .Release.Name }}-staticsite"
      persistentVolumeClaim:
        claimName: "{{ .Release.Name }}-staticsite"
  # @param extraVolumeMounts Array to add extra mount
  #
  extraVolumeMounts:
    - mountPath: /static
      name: "{{ .Release.Name }}-staticsite"

  ## @param initContainers Extra init containers
  ##
  initContainers:
    - name: populate-static
      image: eeproton/scancodeio_web
      command: ['/bin/sh']
      args:
        - '-c'
        - "find /static/ -mindepth 1 -maxdepth 1 -type d -delete && \
          mkdir -p /static/scancodeio /static/scancodeio-static && \
          cp -r /var/scancodeio/static/ /static/scancodeio && \
          cp -r /usr/local/lib/python3.9/site-packages/rest_framework/static/ \
          /static/scancodeio-static && \
          cp -r \
          /usr/local/lib/python3.9/site-packages/django/contrib/admin/static/ \
          /static/scancodeio-static"
      volumeMounts:
        - mountPath: /static
          name: "{{ .Release.Name }}-staticsite"


  ## @param serverBlock Custom server block to be added to NGINX configuration
  serverBlock: |-
    server {
      listen 0.0.0.0:8080;
      root /app;
      location / {
        proxy_pass http://{{ .Release.Name }}-scancodeio-web:8000/;
        proxy_redirect off;
        client_max_body_size 10G;
        proxy_read_timeout 600s;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
      }

      location /static/admin/ {
        alias /static/scancodeio-static/static/admin/;
      }
      location /static/rest_framework {
        alias /static/scancodeio-static/static/rest_framework;
      }
      location /static/ {
        alias /static/scancodeio/static/;
      }
    }
