---
apiVersion: v1
kind: Secret
metadata:
  name: scancode-secret
  labels:
    {{- include "scancodeio.labels" . | nindent 4 }}
type: Opaque
stringData:
  database: scancode-db
  username: scancode-user
  password: scancode-pwd
  postgres-password: scancode-admin-pwd
  SECRET_KEY: sBWLZ0ryiaO15842p0yMS//Zhh7K66wwxn0MmPLwI7nfRPLe/Y
