---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "scancodeio.fullname" . }}-workspace-claim
  labels:
    {{- include "scancodeio.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
